services:
  postgres:
    image: postgres:16-alpine
    container_name: secure-auth-db
    environment:
      POSTGRES_DB: secure-auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql